version: '2'

services:
  web:
    build: ./keras
    ports:
        - "5000:5000"
        - "5001:5001"
        - "5002:5002"
    volumes:
        - ./keras/app:/code
    depends_on:
        - redis
  redis:
    image: redis

  frontend:
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules: